languageCode = "en"
languageName = "English"
weight = 1
title = "hokak's note"

[params]
    displayName = "EN"
    isoCode = "en"
    rtl = false
    dateFormat = "2 January 2006"
    logo = "img/sitelogo.png"
    # secondaryLogo = "img/secondary-logo.png"
    # description = "My awesome website"
    # copyright = "Copy, _right?_ :thinking_face:"

[author]
    name = "hokak"
    image = "img/author.gif"
    imageQuality = 96
    headline = "but nothing here"
    bio = "need more sleep"
    links = [
        { github = "https://github.com/asia-hokak" },
        { instagram = "https://www.instagram.com/hokak_/" },
        { facebook = "https://www.facebook.com/asiahokak/"},
        { steam = "https://steamcommunity.com/id/CreeperSH/"}

    ]
