# -- Markup --
# These settings are required for the theme to function.
[markup]
  [markup.markdown]
    parser = "goldmark" 
    table = true
    math = true

[goldmark]
[goldmark.renderer]
  unsafe = true
  withHardWraps = true

[highlight]
  noClasses = false

[tableOfContents]
  startLevel = 2
  endLevel = 4
