[[main]]
    name = "About"
    pageRef = "about"
    weight = 1

[[main]]
    name = "Posts"
    pageRef = "posts"
    weight = 2

[[main]]
    name = "Writeups"
    pageRef = "writeups"
    weight = 3

[[main]]
    name = "Notes"
    weight = 4

[[main]]
    name = "Web"
    parent = "Notes"
    pageRef = "web"
    weight = 4

[[main]]
    name = "Crypto"
    parent = "Notes"
    pageRef = "crypto"
    weight = 5

[[main]]
    name = "Reverse"
    parent = "Notes"
    pageRef = "reverse"
    weight = 6

[[main]]
    name = "Pwn"
    parent = "Notes"
    pageRef = "pwn"
    weight = 7

[[main]]
    name = "Misc"
    parent = "Notes"
    pageRef = "misc"
    weight = 8

[[main]]
    name = "Algo"
    parent = "Notes"
    pageRef = "algo"
    weight = 9

[[main]]
    name = "Tools"
    parent = "Notes"
    pageRef = "tools"
    weight = 10

[[main]]
    name = "Others"
    parent = "Notes"
    pageRef = "others"
    weight = 11

   