colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true
enableSearch = true
enableCodeCopy = false
replyByEmail = false
disableImageOptimization = false
disableTextInHeader = false
backgroundImageWidth = 1200
defaultBackgroundImage = "img/background.png"
defaultFeaturedImage = "img/article.png"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
[header]
    layout = "basic"

[footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

[homepage]
    layout = "homepage"
    showRecent = true
    showRecentItems = 5
    showMoreLink = false
    showMoreLinkDest = "/posts"
    cardView = false
    cardViewScreenWidth = false
    layoutBackgroundBlur = true

[article]
    defaultBackgroundImage = "img/background.png"
    showDate = false
    showViews = false
    showLikes = false
    showDateOnlyInArticle = false
    showDateUpdated = false
    showAuthor = false
    showHero = true
    heroStyle = "background"
    layoutBackgroundBlur = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = true
    editAppendPath = true
    seriesOpened = true
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    showRelatedContent = true
    relatedContentLimit = 6
    showTaxonomies = true
    showAuthorsBadges = true
    showWordCount = false
    showSummary = true
    showZenMode = false

[list]
    showHero = true

    heroStyle = "background"
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = false
    showSummary = false
    showViews = false
    showLikes = false
    showTableOfContents = 3
    showCards = false
    orderByWeight = false
    groupByYear = false
    cardView = false
    cardViewScreenWidth = false
    constrainItemsWidth = false

[sitemap]
excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
showTermCount = true
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = false
cardView = false

[term]
showHero = false
showBreadcrumbs = false
showViews = false
showLikes = false
showTableOfContents = true
groupByYear = false
cardView = false
cardViewScreenWidth = false

[firebase]

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]
