colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false
enableSearch = true
enableCodeCopy = true
replyByEmail = false
disableImageOptimization = true
disableTextInHeader = false
backgroundImageWidth = 1920
defaultBackgroundImage = "img/article.png"
defaultFeaturedImage = "img/traffic.svg"
giteaDefaultServer = "https://git.fsfe.org"
forgejoDefaultServer = "https://v8.next.forgejo.org"
highlightCurrentMenuArea = true
smartTOC = true
smartTOCHideUnfocusedChildren = false
math = true


[header]
    layout = "fixed"

[footer]
    showMenu = true
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = false
    showScrollToTop = true

[homepage]
    layout = "homepage"
    showRecent = false
    showRecentItems = 6
    showMoreLink = false
    showMoreLinkDest = "/writeups"
    cardView = true
    cardViewScreenWidth = false
    layoutBackgroundBlur = true

[article]
    showDate = true
    showViews = true
    showLikes = true
    showDateOnlyInArticle = false
    showDateUpdated = false
    showAuthor = true
    showHero = true
    heroStyle = "article"
    layoutBackgroundBlur = true
    showBreadcrumbs = false
    showDraftLabel = true
    showEdit = false
    editAppendPath = false
    seriesOpened = true
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    showRelatedContent = false
    relatedContentLimit = 6
    showTaxonomies = true
    showAuthorsBadges = true
    showWordCount = false
    showSummary = true
    showZenMode = true


[list]
    showHero = true
    heroStyle = "background"
    layoutBackgroundBlur = true
    layoutBackgroundHeaderSpace = true
    showBreadcrumbs = true
    showSummary = false
    showViews = false
    showLikes = false
    showTableOfContents = true
    showCards = true
    orderByWeight = false
    groupByYear = false
    cardView = true
    cardViewScreenWidth = false
    constrainItemsWidth = false

[sitemap]
    excludedKinds = [ "taxonomy", "term" ]

[taxonomy]
    showTermCount = true
    showHero = false
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = false
    cardView = false

[term]
    showHero = false
    showBreadcrumbs = false
    showViews = false
    showLikes = false
    showTableOfContents = true
    groupByYear = false
    cardView = false
    cardViewScreenWidth = false

[firebase]
    apiKey = "AIzaSyBr-x1__I9ogctfZ3jB9_Alf-SL8L6OPtA"
    authDomain = "blog-82312.firebaseapp.com"
    projectId = "blog-82312"
    storageBucket = "blog-82312.firebasestorage.app"
    messagingSenderId = "943998431646"
    appId = "1:943998431646:web:2dea172b6ac87bd832e68f"
    measurementId = "G-CDJ2QLLPWR"

[fathomAnalytics]

[umamiAnalytics]

[selineAnalytics]

[buymeacoffee]

[verification]
